job_name = test_$(container_name)

universe = container
container_image = file:///staging/aowen4/apptainer/$(container_name).sif
log = $(job_name).log
batch_name = $(job_name)

executable = /home/aowen4/bin/apptainer_test.sh
transfer_executable = True
arguments = $(container_name)
transfer_input_files = /home/aowen4/bin/apptainer_test.sh

output = $(job_name).out
error = $(job_name).err

requirements = (HasChtcStaging == True) && (OpSysMajorVer > 7)

request_cpus = 4
request_memory = 16GB
request_disk = 30GB

queue

